//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProjectHDO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_contact
    {
        public int contact_id { get; set; }
        public Nullable<int> from_user { get; set; }
        public Nullable<int> to_user { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> mail_id { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual cms_mail cms_mail { get; set; }
    }
}
