//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProjectHDO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ohdEntities : DbContext
    {
        public ohdEntities()
            : base("name=ohdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<Severity> Severities { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<RequestUpdated> RequestUpdateds { get; set; }
        public virtual DbSet<cms_contact> cms_contact { get; set; }
        public virtual DbSet<cms_mail> cms_mail { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Questionnaire> Questionnaires { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<TypeOfFacility> TypeOfFacilities { get; set; }
        public virtual DbSet<comment> comments { get; set; }
    }
}
