//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProjectHDO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaire
    {
        public int qId { get; set; }
        public string question { get; set; }
        public string answer { get; set; }
        public Nullable<int> author { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
