//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProjectHDO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Articles = new HashSet<Article>();
            this.cms_mail = new HashSet<cms_mail>();
            this.Requests = new HashSet<Request>();
            this.Notifications = new HashSet<Notification>();
            this.comments = new HashSet<comment>();
        }
    
        public int UserId { get; set; }
        [Required(ErrorMessage = "Please, enter the username")]
        [RegularExpression("^([a-zA-Z0-9]+)$", ErrorMessage = "Username is not contains special characters!")]
        [StringLength(15, MinimumLength = 5, ErrorMessage = "The length of user must be from 5 to 15 characters")]
        public string username { get; set; }
        [Required(ErrorMessage = "Please, enter the password")]
        public string password { get; set; }
        public string fullname { get; set; }
        public Nullable<bool> gender { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        [Required(ErrorMessage = "Please, enter the email")]
        [EmailAddress(ErrorMessage ="Please, enter valid address email")]
        public string email { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> birthday { get; set; }
        public string favorite { get; set; }
        public Nullable<int> role { get; set; }
        public Nullable<int> facility { get; set; }
        public string avatar { get; set; }
        public Nullable<System.DateTime> timeJoin { get; set; }
        public Nullable<int> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_mail> cms_mail { get; set; }
        public virtual Role Role1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
    }
}
